<?

//Get the name of the file (form.php)
$phpself = basename(__FILE__);
//Get everything from start of PHP_SELF to where $phpself begins
//Cut that part out, and place $phpself after it
$_SERVER['PHP_SELF'] = substr($_SERVER['PHP_SELF'], 0, strpos($_SERVER['PHP_SELF'],
$phpself)) . $phpself;
//You've got a clean PHP_SELF again (y) 


require_once("../config/config.php");

    
// load the login class

// load php-login components
require_once("../php-login.php");

// create a login object. when this object is created, it will do all login/logout stuff automatically
// so this single line handles the entire login process.
$login = new Login();

 
    
// ... ask if we are logged in here:
if ($login->isUserLoggedIn() == true) {    
    // the user is logged in...

$user_id = $_SESSION['user_id'];

include($_SERVER['DOCUMENT_ROOT']."/classes/ad_credit_exchange_class.php");
$adCreditExchange = new adCreditExchange;
$balance_array = $adCreditExchange->getUsersPriceSlotBalance($user_id);
foreach($balance_array as $key=>$value){
$balance = $value['balance'];
}
$balance = number_format($balance, 8, '.', '');



$status = 'offered';
$get_frozen_offered = $adCreditExchange->check_balance($user_id, $status);
$status = 'accepted';
$get_frozen_accepted = $adCreditExchange->check_balance($user_id, $status);


$msg="";

$msg .= '<div><h1 align="center">Buying Your Advertising Credits For Cash</h1> <br><table style = "margin-left:auto; 
    margin-right:auto;" bgcolor="gray" width="75%"><tr><td><p style="text-align:left; font-size: 125%;"> ';


$msg .=   "<div><h1>Details of the step by step process to buy Advertising Credits.</h1></div>";



$msg .=   "
</td></tr></table></div>
<div>
<p><h1 style='color:red'>ATTENTION! BEFORE YOU DEPOSIT ANY MONEY TO A SELLER'S BANK ACCOUNT</H1>
<UL>
<LI>THERE ARE TWO TIME LIMITS INCORPORATED INTO THE ADVERTISING CREDITS SALES AGREEMENTS. REGARDING THESE TWO TIME LIMITS KNOW THAT \"TIME IS OF THE ESSENCE\" FOR ANY AND ALL TIME LIMITS PLACED ON SELLERS AND BUYER (look that term up if you do not know what it means)</LI>
<LI>BUNGEEBONES FREEZES THE CREDITS AND PROTECTS AND SECURES THEM FOR THE BUYER TO PROVIDE TIME FOR THE BUYER TO DEPOSIT CASH INTO A SELLER'S BANK</LI>
<LI>BUNGEEBONES <B>NEVER</B> RECEIVES DEPOSITS ON THE SELLER'S BEHALF</LI>
<LI>SUGGESTED PRACTICE IS FOR A BUYER TO TRAVEL TO THE SELLER'S BANK FIRST (BEFORE COMMITTING TO BUY) AND COMMIT TO PURCHASE VIA SMARTPHONE OR LAPTOP WHILE AT OR NEAR THE BANK TO REDUCE THE RISK OF UNFORESEEN EVENTS THAT WOULD PREVENT THE DEPOSIT FROM HAPPENING AS PLANNED</LI>
<LI>WHILE A DEFAULT OF A BUYER TO MAKE A TIMELY DEPOSIT IS NOT LOOKED AT VERY HIGHLY, THE DEFAULT OF A BUYER TO MAKE A REPORT AFTER THEY MAKE A DEPOSIT COULD BE CATASTROPHIC FOR THE BUYER SINCE THE ADVERTISING CREDITS WILL BE TRANSFERRED BACK TO THE SELLER (AND OUT OF BUNGEEBONES CONTROL) WITHOUT THE REPORT FROM THE BUYER (TIME BEING OF THE ESSENCE).
<LI>YOU WILL BE PROVIDED THE SELLER'S ACTUAL BANK ACCOUNT NUMBER SO THAT YOU CAN MAKE A DEPOSIT TO THE SELLER'S ACCOUNT</LI>
<LI>IT IS SUGGESTED (BUT NOT REQUIRED) THAT THE SELLER PROVIDE THE NAME ASSOCIATED WITH THE ACCOUNT FOR ADDED SECURITY - THE SELLER ASSUMES ALL RESPONSIBLITY TO PROVIDE THE CORRECT ACCOUNT NUMBER WHILE THE BUYER ASSUMES THE RESPONSIBILTY TO COPY THE ACCOUNT NUMBER ACCURATELY TO THE DEPOSIT SLIP</LI>
<LI>IF/WHEN YOU ACCEPT AN OFFER THE CREDITS BECOME \"HARD\" FROZEN AND IT WILL NOT BE POSSIBLE TO FOR THE SELLER TO CANCEL OR RETRIEVE THEM AT LEAST FOR THE DURATION OF THE <B>1ST</B> TIME PERIOD ALLOCATED TO ALLOW YOU, THE BUYER, TO MAKE AND CONFIRM THE DEPOSIT </LI>
<LI>AFTER YOU MAKE THE CASH DEPOSIT TO THE SELLER'S BANK AND REPORT BACK YOUR SUCCESS (THROUGH BUNGEEBONES) THE SELLER WILL BE NOTIFIED (BY BUNGEEBONES) BY EMAIL IMMEDIATELY AND HAS AS LONG AS THE <b>2ND</b> TIME PERIOD SPECIFIED TO VERIFY THE DEPOSIT</LI>
<LI>AFTER THAT 2ND TIME PERIOD HAS ELAPSED THE CREDITS WILL BE TRANSFERRED TO YOU AUTOMATICALLY UNLESS THE SELLER FILES A CLAIM FOR ARBITRATION FROM BUNGEEBONES ADMINISTRATION
<li>IN REGARDS TO BOTH THOSE TIME PERIODS \"TIME IS OF THE ESSENCE\". IF YOU DON'T KNOW THE LEGAL MEANING OF THAT PHRASE THEN RESEARCH IT OR CONSULT AN ATTORNEY.</li>
<LI>AFTER YOU REPORT BACK OF THE SUCCESSFUL DEPOSIT (WITHIN THE ALLOTED TIME), THE 2ND TIME PERIOD WILL BE THE SELLER'S ONLY AND FINAL OPPORTUNITY TO HALT THE TRANSACTION AND ONLY IF YOU HAVE NOT ACTUALLY MADE THE DEPOSIT AS YOU REPORTED OR MADE A DEPOSIT OF A LESSER AMOUNT THAN REQUIRED - IT IS ENTIRELY THE RESPONSIBILITY OF THE SELLERS TO DETECT ANY FRAUDULENT DEPOSIT REPORTS WITHIN THE SPECIFIED TIME</LI>
<LI>AFTER THE SELLER CONFIRMS THAT THE DEPOSIT HAS, INDEED, BEEN CORRECTLY MADE THEY CAN IMMEDIATELY TRANSFER THE CREDITS TO THE BUYER THEMSELF OR IT WILL BE DONE AUTOMATICALLY AT THE END OF THE <B>2ND</B> TIME PERIOD.  </LI>
<LI>IF THE SELLER DISCOVERS THAT THE BUYER FALSELY REPORTED A DEPOSIT THEN THEY WOULD SUBMIT THE MATTER FOR ARBITRATION TO BUNGEEBONES - DOING SO WILL CANCEL THE AUTOMATIC TRANSFER BUT THE CREDITS STILL REMAIN FROZEN .</LI>
<LI>BUNGEEBONES WILL CONTACT YOU WITH A REQUEST FOR PROOF OF THE DEPOSIT (I.E. ASKING FOR A COPY OF THE DEPOSIT SLIP) </LI>
<LI>LACK OF A TIMELY RESPONSE FROM THE BUYER SIGNIFIES DEFAULT AND THE CREDITS WILL BE REMOVED FROM DEEP FREEZE AND RETURNED TO THE SELLER</LI>
<LI>RECEIPT OF A DEPOSIT SLIP CONFIRMING THE AGREED UPON AMOUNT WILL RESULT IN A REQUEST TO THE SELLER TO PROVIDE A COPY OF THEIR BANK DEPOSIT RECORDS</LI>
<LI>LACK OF A TIMELY RESPONSE FROM THE SELLER SIGNIFIES DEFAULT AND IN THE CREDITS BEING TRANSFERRED BY BUNGEEBONES ADMINISTRATION TO THE BUYER</LI>
<LI>BANK RECORDS CONFIRMING THE BUYER'S DEPOSIT WILL, LIKEWISE, CAUSE THE CREDITS BEING TRANSFERRED BY BUNGEEBONES ADMINISTRATION TO THE BUYER'S ACCOUNT</LI>
<LI>IF THE SELLER IS RESPONSIBLE FOR FALSE REPORTING THEN A FEE OF 10% OF THE TRANSACTION SHALL BE CHARGED TO THE SELLER AND SPLIT EQUALLY BETWEEN BUNGEEBONES AND THE BUYER FOR DAMAGES</LI>
<LI>ARBITRATION MAY BE RESOLVED IN VARIOUS WAYS SUCH AS PARTIAL PAYMENTS AT THE DISCRETION OF THE BUNGEEBONES ADMINISTRATION</LI>
<LI>IF THE DOCUMENTATION SUPPLIED BY THE BUYER AND SELLER DO NOT MATCH THEN THERE ARE ONLY A COUPLE OF POSSIBILITIES 1) BANK ERROR 2) FRAUD ON THE PART OF EITHER THE BUYER OR THE SELLER BY PHOTO EDITING THE DOCUMENTS. <B>IN SUCH INSTANCES BUNGEEBONES RESERVES THE RIGHT TO USE AN INDEFINITE TIME TO RESOLVE THE MATTER AND THE CREDITS WILL CONTINUE TO BE DEEP FROZEN (I.E. NOT DISBURSED TO EITHER PARTY) FOR AN INDEFINITE TIME UNTIL THE ISSUE IS RESOLVED</LI>
<LI>ALL DECISIONS BY BUNGEEBONES ADMINISTRATION ARE FINAL</LI>
<LI>ALL TRANSFERS OF CREDITS WHETHER MANUALLY OR AUTOMATICALLY ARE FINAL</LI>
</div>

";





echo $msg;
echo '<h2><u>Close This Modal Page To Return To Advertising Credit Exchange Menu</u></h2></a>';
} else {
    // the user is not logged in...
    include("../views/not_logged_in.php");
}

