<table><tr><td colspan=2>Here is a screen shot of an example menu for choosing your placement position.</td></tr>
<tr><td><img src="../../images/how_to_buy.jpg"></td><td  valign="top"><p></p>Notice the yellow blocks with the radio buttons (if you don't see yellow blocks or radio buttons in your own control panel and, instead see just a single check box it is because there have not been any price slots purchased in that category yet which would place you in the top position if you grab it). Each one is for a different price and enables you to place your link in what is called a "price slot". For now, it is enough to understand that links are displayed according to the price slot they are in (from the highest to the lowest) and all links in price slots are listed ahead of the free sites.</p>
<p><i>Bid strategy #1 - Placing your link in even the lowest price slot (which is priced for an entire month at what just one click would cost in a PPC program) will jump your listing ahead of ALL the free links! You can see how much traffic your category gets from the "Add a link" wizard available from the top  menu of your BungeeBones User CP. Migrate to the category you want the stats for and scroll down to the dropdown menu.</i></p>
<p>Notice that below the yellow blocks it reports how many links there are that have bought in that particular price slot. In other words, there can be an unlimited number of listings in the same price slot. Within a price slot, links are ordered according to seniority. The first one to buy in a price slot retains top position in THAT PRICE SLOT for as long as there is enough in their account to pay that daily fee. The fee will never change significantly unless they move their link to a different price slots. Note there is some slight change in price because base prices are set on a per-month basis and payment is made daily so, depending on the number of days there are that month the per-diem may change slightly.</p>
</td></tr>
<tr><td colspan=2><p><i>Bid strategy #2 - As more links populate a given price slot it pays to be the first to buy in the next higher price slot because you will be first on the page (until someone buys in a higher price slot).</i></p>
<p>Notice that there is a pattern to the price increases. The lowest priced slot is priced at about what one click in a leading Pay Per Click program would cost you. The next highest slot is one and a half times what the first one is. The third slot is one and a half times what the second slot is. And that pattern continues because everytime someone is the first to buy in the top slot the script automatically creates a new, empty top slot at one and a half times the previous price.</p>
<p><i>Bid strategy #3 - While this system enables a certain level of competition and bidding (so we can pay our partner websites for their traffic contributions), it is possible for a bidder to allow the listing to "float" up and down in the listings and only have to check back every once in a while to see their status and position in the category (they can also just view the BungeeBones web directory in any one of the remote locations or at BungeeBones.com to see it also). By bidding into the number one spot, for example, there would have to be twenty others to come and pay one and a half times as much as you before your link was off the first page.</i></p>
<p><h2>How To Save 50%</h2></p>
<p>Perhaps you might be interested in learning how to save 50% in your own advertising fees. As mentioned, we pay our partners (i.e. the websites that host BungeeBones directories on their own sites) commissions on sales they make so, if you add the web directory to your website then YOU become your own first customer!</p>
<p><i>Bid strategy #4 - Gain a major price advantage (50%) by adding the BungeeBones web directory to your website and become your own best web advertising customer.</i></p>

<p><h2>Change Or Exchange A Purchase</h2></p>
<p>You can upgrade or downgrade your priceslot purchase at any time. Simply select the new price slot's radio button. Your current price slot will be canceled and you will be subscribed in the new one. 
<p><h2>How To Cancel An Existing Bid/Purchase</h2></p>
<p>The cancelation of a previous purchase can be done easily by selecting the radio for the SAME AMOUNT that you purchased it for. We won't let you forget the amount because you will be able to see it listed in red, just above the radio buttons after you purchase, <br>and saying <br>
<font color=red>Your Current Slot Price 
<br>Is Indicated Above 
</font>. <br><b>Select the radio button of the same amount as what is listed in your report there.</b></p>
</td></tr>
</table>
