<table><tr><td colspan=2>Here is a screen shot of an example menu for choosing to update your placement position.</td></tr>
<tr><td><img src="../../images/check_box_bid.jpg"></td><td  valign="top"><p>A BungeeBones user control panel may display a single checkbox like the example below or a series of yellow blocks with a single radio button in each (not shown). If you have multiple links added to the BungeeBones web directory you may have both types of menus in your CP. The reason for the single checkbox is that you are about to become the first and top bidder. By being the first you will remain in the top position in that price slot as long as you continue paying the monthly fee but if someone purchases in a higher price slot then they will "leap-frog" ahead of you. </p> 
For now, it is enough to understand that links are displayed according to the price slot they are in (from the highest to the lowest) and all links in price slots are listed ahead of the free sites. Your site will be in the lowest price slot but still ahead of all the free sites.</p>
<p><i>Bid strategy #1 - Placing your link in even the lowest price slot (which is priced for an entire month at what just one click would cost in a PPC program) will jump your listing ahead of ALL the free links! You can see how much traffic your category gets from the "Add a link" wizard available from the top  menu of your BungeeBones User CP. Migrate to the category you want the stats for and scroll down to the dropdown menu.</i></p>
<p>Be aware that there can be an unlimited number of listings in the same price slot. Within a price slot, links are ordered according to seniority. The first one to buy in a price slot retains top position in THAT PRICE SLOT for as long as they pay that monthly fee. The fee will never change unless they move their link to a different price slots.</p>
</td></tr>
<tr><td colspan=2><p><i>Bid strategy #2 - As more links populate a given price slot it pays to be the first to buy in the next higher price slot because you will be first on the page (until someone else buys in yet another higher price slot).</i></p>
<p>After you purchase the checkbox menu disappears in favor of the radio buttons and there will be two. Everytime someone purchases the new price slot another will be created. Each new price slot is for a higher price. There is a pattern to the price increases that you may notice. The lowest priced slot is priced at about what one click in a leading Pay Per Click program would cost. The next highest slot is double what the first one is. The third slot is double what the second slot is. And that pattern continues because everytime someone is the first to buy in the top slot the script automatically creates a new, empty top slot at twice the price.</p>
<p><i>Bid strategy #3 - While this system enables a certain level of competition and bidding (so we can pay our partner websites for their traffic contributions), it is possible for a bidder to allow the listing to "float" up and down in the listings page and only have to check back every once in a while to see their status and position in the category (they can also just view the BungeeBones web directory in any one of the remote locations or at BungeeBones.com to see it also). By bidding into the number one spot, for example, there would have to be twenty others to come and pay twice as much as you before your link was off the first page.</i></p>
<p>Perhaps you might be interested in learning how to save 50% in your own advertising fees. As mentioned, we pay our partners (i.e. the websites that host BungeeBones directories on their own sites) commissions on sales they make so, if you add the web directory to your website then YOU become your own first customer!</p>
<p><i>Bid strategy #4 - Gain a major price advantage (50%) by adding the BungeeBones web directory to your website and become your own best web advertising customer.</i></p>
</td></tr>
<tr><td><img src="../../images/how_to_buy.jpg"></td><td  valign="top">
<p><h2>Change Or Exchange A Purchase</h2></p>
<p>After your purchase the menu will change to something similar to the example on the left with two radio buttons. After you purchase you can upgrade or downgrade your priceslot at any time. Simply select the new price slot's radio button. Your account will get credited with the remainder of that months fees from your current price slot purchase and will purchase the new one. The new one, too, will be prorated as well
<p><h2>How To Cancel An Existing Bid/Purchase</h2></p>
<p>After you purchase, the cancelation of a previous purchase can be done easily by selecting from among the radio buttons that will appear after your purchase. Select the radio button for the SAME AMOUNT that you purchased it for. We won't let you forget the amount because you will be able to see it listed in red, just above the radio buttons after you purchase, <br>and saying <br><font color=red>Current Subscription 
<br>(select to cancel)<br>$xx.xx/mo</font>. <br><b>Select the radio button of the same amount as what is listed in your report there.</b>The prorating calculations will be done for any remaining, unused time that you had paid for and your account will be credited for the unused portion of the fee you already paid.</p>
</td></tr>
</table>