<!--<h2>Purchasing Advertising Credits (a.k.a. AdCoins*) To Fund Your Account</h2>
<p align="left">A brief explanation of of the payment and accounting system is needed before we get into funding an individual account. First, all payments into and out of the BungeeBones network are made using Bitcoin (no cash, checks, PayPal, USD, Euros, Yen etc.). For security reasons and because of security breeches at a number of exchanges in Bitcoin's history, all Bitcoin deposits go immediately to offline, cold storage wallet which are impervious to hackers. They remain in cold storage until such time as users request to redeem them. At the time of deposit they are credited to the user's account as "Adcoin" which are psuedonyms for Bitcoin because they trade or are redeemable on a one for one exchange rate. In other words, Adcoin are a fictitious alt coin backed by real Bitcoin and/or advertising services. The term "advertising credits" are used interchangeably with the term Adcoins as well.

<p align="left">Advertisers would normally need to fund their accounts with Bitcoin in order to pay for their advertising. Those payments of Bitcoin mostly are paid to the webmasters that host web directories that supply the network's traffic. The accounting system for their earnings also uses the term AdCoin and they can use them internally within BungeeBones to purchase advertising for their own websites or they can redeem them 1 to 1 for Bitcoin through BungeeBones. 

<p align="left"><i>*Since AdCoins are pegged to the Bitcoin price they are as good as Bitcoin within the BungeeBones platform. We store all Bitcoin offline in cold storage so the term "AdCoin" is merely a way to refer to the online, read-only Bitcoin balances. Partners and affiliates earn AdCoin through commissions for making advertising sales. F.Y.I the difference between a partner and an affiliate in our system is that a partner hosts our advertising web directory page on their website (which in turn advertises your website too) while an affiliate does not. That means our affiliates are not able to spend their AdCoin for advertising like our partners can (sic. partners can use their earnings to advertise their own website in our network). It also means our affiliates are usually wanting to trade their AdCoins for local currency while our partners have the additional option to use them for their own advertising.</i>

<hr>
-->
<h2>Purchasing Advertising Credits (a.k.a. AdCoins*) To Fund Your Account - How It Works</h2>
<p>In this new exchange system BungeeBones provides an almost completely automated escrow service for the risk free transfer of existing advertising credits from our members to advertisers/buyers.  This service enables sellers to sell their AdCoins directly to advertisers for cash and, for them, skips the process of having to turn them into Bitcoin first. For the buyer, the process might be less expensive might be more convenient than getting Bitcoin. It all depends. Bungeebones benefits because the liquidity of Advertising Credits/Adcoin is improved for our affiliates and partners and our advertisers get another way to acquire Advertising Credits (besides Bitcoin) through depositing cash to the seller's bank account.</p>
<ol><li>The automated process walks the sellers and the buyers through the steps but buyers and sellers are completely responsible for working out the details of their own trades.</li>
<li>Buyers contract with sellers with offers to buy the credits according to the terms posted by the sellers.</li>
<li>Sellers can withdraw the offer any time before being accepted by a buyer but after a buyer accepts the terms of the offer the Adcoin/advertising credits are frozen by BungeeBones for a certain time period specified in the offer. This time period is to enable the buyer to get to the seller's bank and make a cash deposit. Realize that with a smart phone or laptop a buyer could literrally be in front of the seller's bank before committing to purchase and would need only a few minutes to make a deposit after committing to buy them.</li>
<li>After the buyer reports the successful deposit to BungeeBones via the Internet then that time limit no longer applies and a new time limit starts. This time it is on the seller and is to give them time to confirm the deposit is made. This time limit is generally longer than the one given to the buyer for a number of reasons (ex. the buyer can make the deposit any time, day or night through ATMs, they can make false reports of fictitious deposits any time day or night etc). The seller gives themselves ample time to receive the report and to then be able to check their bank account to confirm the deposit. During this time the credits are still frozen and cannot be used or transferred by the seller. 
<li>Upon confirming the deposit has been made the seller can immediately transfer the credits to the buyer</li>
<li>An additional protection layer for the buyer exists because if for whatever reason the seller fails to transfer the credits they get transferred to the buyer automatically. The ONLY WAY a seller can prevent the automatic transfer is to file an arbitration request with BungeeBones charging fraud or mistake against the buyer. That stops the transfer but the funds are still frozen. 
<li>BungeeBones can function as an arbiter in cases where the deal goes wrong and can ensure buyers receive advertising credits purchased but does not negotiate price or terms.</li>
<li>BungeeBones provides a communication procedure that buyers and sellers are required to follow for arbitration to be available that is a safe, secure and encrypted communication method between all the parties and that requires they get the Bitmessage system.</li>
<li>The choice of payment method is at the discretion of the parties alone but arbitraion will only be provided by BungeeBones for cash deposits to the seller's bank account. This provides a method where it can be confirmed by the seller before transfer of AdCoins to the buyer. Transfer of their AdCoins advertising credits to buyers is irreversable because the transfer of cash to the seller's bank is irreversable. Sellers and buyers can use alternative payment methods but at their own risk. </li>
<li>Sellers are responsible to verify that the funds have been deposited by the buyer. </li>
<li>Buyes are responsible for making the deposit AND for reporting back to BungeeBones that it has occured. Deposits made after the time limit are at the buyer's risk.</>
<li>All arbitration decisions by BungeeBones are final</li>
<li>The buyer that uses the seller's bank ends up with a deposit receipt as proof of deposit and it is suggested they also get a business card or ID of the teller handling the cash transaction and perhaps even a photo of them at the seller's bank</li>

<li>If for any reason the seller fails to transfer the AdCoins advertising credits to the buyer within the 24 hour allotted time period (after buyer notifies seller of a completed deposit) then the buyer can contact BungeeBones for arbitration</li>

<li>A 5% arbitration fee will be charged to the seller in those cases where arbitration is performed</li>
</ol>

<p align="left">Sellers offering their advertising credits must provide 1) Their bank name (so buyers don't commit to making deposits in banks not near to them) 2) Their bank account number and the name associated with the account. This information is found on any check and is public information but BungeeBones stores is encrypted and only provides it to buyers that have agreed to purchase. The information can be deleted or retained for future use according to the seller's settings 4) a time period or deadline for the buyer to complete the deposit and another time limit for the automatic transfer/file arbitration deadline 5) the price.

<p align="left"><a href='../modal/get_AdCoins_fs_list.php' title='General Instructions' rel='gb_page_center[640, 480]'><div style=\"background-image: url('images960/1x1tran.gif'); background-repeat: repeat-x; background-color: navy; color:white; font-size:100%;-moz-border-radius: 15px;
		border-radius: 15px;text-align: center;\">&nbsp;Click Here To See AdCoins For Sale Listings&nbsp;</div></a>

<h2><a href="http://bungeebones.com/members/modal/general_instructions.php?link_id=$db_idp[$key]">Back To Previous Modal Window</a></h2>


