<table><tr><td><h1   id="CA">The BungeeBones Asset Backed Exchange.</h2>

<p>There has so far tended to be a problem getting in and out of Bitcoin (or any alt coin for that matter) but the gathering in one central area in order to do such things as "price discovery" is the essence of the free market. It seems even if you were to do some clandenstine, off the block chain trade you would still need to know what "the market" is paying in order to get a handle on the value of what you have.

<p>Basically all this system provides is a community meeting place in the form of a bulletin board together with an automatic escrow functionality. When everything goes right between the seller and the buyer then that will be the limit of our participation. In the worse case scenario, when something happens during the transaction where the buyer or the seller feel the other party didn't meet their obligations, we can very reluctantly step in as  arbitrator. But our step by step exchange process hopefully removes any incentives to "cheat" so that will hopefully be extremely rare. Read the following steps and decide for yourself if you think there is a loophole. If you find one then please notify us and/or offer a suggestion on how to fix it. Let's make this a model of how to run an asset or service backed exchange that any small business can use to help their customers convert Bitcoin to a local currency.</p>

<h2   id="C1">The First Step - Decide How Much You Are Going To Sell?</h2>
<p>There are only a few rules that would apply and they are pretty straight forward. First, you can't sell more advertising credits than what you own (the system won't let you). In the first input box enter the amount from your account that you want to sell for cash. If you want, you can add more Advertising Credits to your account by depositing Bitcoin to your account which will show up as Advertising Credits rather quickly.</p>
<h2>What Price Are You Asking?</h2>
<p>The difficulty with pricing Bitcoin is its volatility. In order to mitigate the risk we enable you to place time limits for your exposure to price volatility (more about this feature in a little while). You have the choice of putting it up for sale at a price you set or at "market" price. We use Bitstamp's report as the benchmark price. From that benchmark price you can ask up to 15% more than "market" and the software will maintain that ratio for the entire time it is for sale.</p>

<h2>Changing Your Mind</h2>
<p>You can remove your Advertising Credits from the market with the click of a mouse. It is that simple to remove them from the for sale list. The only caveat to that statement is if the offer to sell that you made has been accepted by a buyer already. If they have we have no way to know whether or not they paid you already but since you made an offer, and they accepted your offer then most would say you are already contracted and BungeeBones cannot interfere. 
<h2>Time Limits To Perform Protect Both The Seller And The Buyer</h2>
<p>There are two time limits established by the seller when they place their advertising credits up for sale.</p>
<h3    id="C2">Time Limit #1</h3>
<p>The first time limit is established to prevent a buyer from "parking on a bid" to speculate with the seller's money. Without a time limit they would be able to tie up the seller's Bitcoin and wait for the price to go up without making any investment of their own. So the timer setting establishes how much time the BUYER has after they click "Accept" to get their cash into the seller's bank account AND to also notify the seller that they did. Realize that with a Smart Phone a buyer could "accept" the offer pulling up to the teller at the bank's drive through and could "report" the deposit as they leave the bank. It could all happen in less than two minutes. 
<h3   id="C3">Time Limit #2</h3>
<p>The second time limit is a self induced limit on the seller by the seller with which they commit to delivering the Advertising Credits to the buyer within a certain amount of time from when the buyer submits the notice that they deposited the payment. This time limit is less critical than the first. Since the Advertising Credits are "frozen" when they are posted and "Deep Frozen"  (meaning they can no longer be withdrawn from the market by the seller) when the buyer deposits the money and reports it, the buyer, then, has considerable assurance that they will not be double spent or moved on him. The only concern is to make certain that the seller follows through and performs the simple task of clicking a link that transfers the funds from their BungeeBones account to the buyer's. A seller should obviously check their bank account first to make certain that the deposit was, indeed, recorded but after that it is simply a matter of the seller getting on the Internet and the BungeeBones website in order to complete the transfer. We made it convenient for you to finalize the deal by making the transfer form accessible from your Smart Phone's browser.
<h3>What Happens If ...?</h3>
<p>Now just a promise alone from the seller to transfer might not be enough assurance to a buyer who just put cash into someone else's bank account. So we gave the program a little more "teeth" when we set it up that the seller's own time limit will also trigger an automatic transfer of the Advertising credits to the buyer when the time limit expires.
<p>So with the "Deep Freeze" on his account and the automatic transfer pending at the expiration of his own set time limit the seller is all but totally committed. There is only one more potential "gotcha". Suppose a buyer only reported the deposit and never actually made it? That possibility exists but it is entirely in the seller's ability to find that out by visiting their bank in whatever manner they wish and confirming the deposit. It is the SELLER's last window of opportunity to put a squash on the deal but he can only do so by filing a request for arbitration from BungeeBones. The only possible way that the transfer won't go through is through intervention by BungeeBones Administration. The only reason possible that BungeeBones would rule in the seller's favor is if the buyer never deposited the funds. But the buyer should have a deposit receipt from the bank and, what we recommmend also, is a business card from the teller that handled the transaction. The buyer could then submit copies of those documents as proof of the deposit.
<p>The only party that operates without a time limit is BungeeBones arbitration. If the two parties are locked in a battle of fraudulent documents and claims then we can take as long as we want to get at the truth. And during that time the advertising credits are stored safely away awaiting their return to their rightful owner (whomever that might be).
</td></tr>
</table>
