<?php
//echo '<br>in common';
$welcome_message = "<h1>Select Your Ad Position</h1>
<p>Notice: your website submission for distribution in the Manna Network is currently pending administrative review (standard practice). Your ad will only be live after that process. You can still place a bid for better position. As you will learn, the time of your purchase estab;lishes your seniority in that price slot. Manna Network's policy is that your subscription will receive the date/time when you purchase/bid (below) and is not affected by any delays in approving your website.
<p>Selecting from the below list of \"Price Slots\" will enroll your site (on a subscription type basis) for placement in a \"relative and tenatative\" across the entire Manna Network Distributed Ad Network.  
<p>\"Relative and tenatative\" means that the order that ads are actually displayed in is subject to change DAILY. The order is determined daily when new bids and subscriptions are compared and the links are ordered in the following priorities: 1) the coin type (BSV paying bids are listed first, Demo Coin bids next and then, lastly free links) 2) Within those three groupings the links are ordered according to the Price Slot selected (highest to lowest) and 3) Seniority (determined by when the price slot subscription was first acquired). Note that seniority orders the links when there is multiple subscribers to the same price slot and also the remaining free advertisers.
<p>Purchases are \"relative and tentative\" because other higher or lower payments can and do arrive that can move your ad higher or lower in the display. Most of the time these movements up or down are minor and occur slowly over time but can also be volatile (escpecially if the crypto prices have been volatile). As the value of the BSV changes, so too does the value you are paying for your price slot. Yourself and others will react differently to the trends and move their placement accordingly. 
<p> Notice that the next higher price slot will always be priced 1.5 times the next lower one.";
?>
