<!--

//this is the menu copied from the working nirvana tempalte on bb.xyz on oct 12, 2015 preparing for update of bb.com
// include($_SERVER['DOCUMENT_ROOT']."/nirv_temps/nirv_temp_top.php");
//<div class="menu">  -->

<ul><li ><a href="http://bungeebones.xyz/"><span>Home</span></a></li><li class="page_item page-item-29"><a href="http://bungeebones.xyz/about/"><span>About</span></a></li><li class="page_item page-item-84 page_item_has_children current_page_item"><a href="http://bungeebones.xyz/open-business-model/"><span>Open Business Model</span></a><ul class='children'><li class="page_item page-item-38"><a href="http://bungeebones.xyz/open-business-model/a-web-traffic-co-operative/"><span>A Web Traffic Co-Operative</span></a></li><li class="page_item page-item-56"><a href="http://bungeebones.xyz/open-business-model/earn/"><span>Compare Co-Op To PPC</span></a></li><li class="page_item page-item-34"><a href="http://bungeebones.xyz/open-business-model/a-website-operator-multi-stakeholder-co-operative/"><span>A Multi-Stakeholder Co-Operative</span></a></li><li class="page_item page-item-44"><a href="http://bungeebones.xyz/open-business-model/a-web-traffic-mls/"><span>A Web Traffic MLS</span></a></li><li class="page_item page-item-95"><a href="http://bungeebones.xyz/open-business-model/ownership-of-the-cooperative/"><span>Ownership Of The CoOperative</span></a></li></ul></li><li class="page_item page-item-86 page_item_has_children"><a href="http://bungeebones.xyz/marketing/"><span>Marketing</span></a><ul class='children'><li class="page_item page-item-91"><a href="http://bungeebones.xyz/marketing/defining-white-hat-mlm/"><span>Defining White Hat MLM</span></a></li><li class="page_item page-item-88"><a href="http://bungeebones.xyz/marketing/why-i-decided-on-mlm/"><span>Why I Decided On MLM</span></a></li><li class="page_item page-item-98"><a href="http://bungeebones.xyz/marketing/mlm-commission-tree/"><span>MLM Commission Tree</span></a></li><li class="page_item page-item-52"><a href="http://bungeebones.xyz/marketing/network-effects/"><span>Network Effect(s)</span></a></li></ul></li><li class="page_item page-item-64 page_item_has_children"><a href="http://bungeebones.xyz/earn-bitcoin/"><span>Earn Bitcoin</span></a><ul class='children'><li class="page_item page-item-70"><a href="http://bungeebones.xyz/earn-bitcoin/how-to-redeem/"><span>How To Redeem</span></a></li></ul></li><li class="page_item page-item-81"><a href="http://bungeebones.xyz/our-api/"><span>Our API</span></a></li><li class="page_item page-item-108"><a href="http://bungeebones.xyz/contact/"><span>Contact</span></a></li></ul>

<!--</div>-->

?>
